//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiagnoseResult
    {
        public int DiagnoseResultID { get; set; }
        public System.DateTime Date { get; set; }
        public string Result { get; set; }
        public string Direction { get; set; }
        public int ExaminationFormID { get; set; }
        public int PatientID { get; set; }
        public int GPID { get; set; }
    
        public virtual ExaminationForm ExaminationForm { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
