//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugInvoiceDetail
    {
        public Nullable<int> Quantity { get; set; }
        public int InvoiceID { get; set; }
        public int DrugID { get; set; }
        public int ID { get; set; }
    
        public virtual Drug Drug { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
