//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminationForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExaminationForm()
        {
            this.DiagnoseResults = new HashSet<DiagnoseResult>();
        }
    
        public int ExaminationFormID { get; set; }
        public Nullable<int> Ordinal { get; set; }
        public System.DateTime Date { get; set; }
        public string Reason { get; set; }
        public string State { get; set; }
        public int PatientID { get; set; }
        public int SecretaryID { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DiagnoseResult> DiagnoseResults { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
