//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPdrugDetail
    {
        public int GPdrugID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public int PrescriptionID { get; set; }
        public int PatientID { get; set; }
        public int GPID { get; set; }
        public string NameDrug { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
