//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.DrugInvoiceDetails = new HashSet<DrugInvoiceDetail>();
            this.ExaminationInvoiceDetails = new HashSet<ExaminationInvoiceDetail>();
        }
    
        public int InvoiceID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public int PatientID { get; set; }
        public int PharmacistID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugInvoiceDetail> DrugInvoiceDetails { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExaminationInvoiceDetail> ExaminationInvoiceDetails { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
