//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicalTreatmentEntities : DbContext
    {
        public MedicalTreatmentEntities()
            : base("name=MedicalTreatmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<DiagnoseResult> DiagnoseResults { get; set; }
        public virtual DbSet<Drug> Drugs { get; set; }
        public virtual DbSet<DrugInvoiceDetail> DrugInvoiceDetails { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<ExaminationForm> ExaminationForms { get; set; }
        public virtual DbSet<ExaminationInvoiceDetail> ExaminationInvoiceDetails { get; set; }
        public virtual DbSet<GPdrugDetail> GPdrugDetails { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PaySalary> PaySalaries { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<SpecialistExamination> SpecialistExaminations { get; set; }
        public virtual DbSet<SpecialistExaminationRequest> SpecialistExaminationRequests { get; set; }
        public virtual DbSet<SpecialistExaminationResult> SpecialistExaminationResults { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
