//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialistExaminationResult
    {
        public int SEresultID { get; set; }
        public System.DateTime Date { get; set; }
        public string Result { get; set; }
        public string Conclusion { get; set; }
        public int SpecialExaminationID { get; set; }
        public int PatientID { get; set; }
        public int SpecialistID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual SpecialistExamination SpecialistExamination { get; set; }
    }
}
